### ISSUE TITLE
Handling Large SLEAP File (460MB) in the App

### ISSUE THREAD

**Issue by Freddie-Faulich** [Lightning-Universe/Pose-app#107] opened 2024-08-13 11:23 UTC
Hi everyone,

I'm working with a SLEAP file that is approximately 460MB in size. I’m wondering if there’s a way to effectively use such a large file within the app. Any advice or tips would be greatly appreciated.

Best regards

**Comment by Freddie-Faulich** [comment] 2024-08-14 08:52
I tried that, but I can't find my labeled images anywhere

**Comment by Shmuel-columbia** [comment] 2024-08-14 13:59
Hi @Freddie-Faulich, Can you please elaborate on what you are trying to do? Are you trying to export labeled images from SLEAP and import them to the app?

**Comment by Freddie-Faulich** [comment] 2024-08-14 14:07
Yes that's exactly what I'm trying to do! Is this possible?

**Comment by Shmuel-columbia** [comment] 2024-08-14 14:27
In your SLEAP project go to: predict > export labels package > labeled frames 
you should get an pkg.slp file, which you can import to Lightning Pose App by selecting: create new project from sourch > SLEAP. 
Launch the app as instructed in the FAQ link above if your file size is larger than 200MB. 
Here is a link to our [docs](https://pose-app.readthedocs.io/en/latest/source/using_the_app.html) for further instruction.

let us know if you have any questions. 
Here to help!

**Comment by Freddie-Faulich** [comment] 2024-08-16 09:34
That's what I did, should my labeled data be visible anywhere in the GUI?

**Comment by Freddie-Faulich** [comment] 2024-08-28 12:19
I use the app as intended but when i try to updoad my data the app stops unexpectedly, and I receive the following error:

INFO: Your Lightning App is being stopped. This won't take long.
INFO: Your Lightning App has been stopped successfully!
INFO: Received SIGTERM signal. Gracefully terminating train_ui.work...
INFO: Received SIGTERM signal. Gracefully terminating streamlit_frame.work...
INFO: Received SIGTERM signal. Gracefully terminating tensorboard...
INFO: Received SIGTERM signal. Gracefully terminating label_studio.label_studio...
INFO: Received SIGTERM signal. Gracefully terminating fiftyone...
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/bin/lightning_app", line 8, in <module>
    sys.exit(_cli_entry_point())
  ...
  File "/teamspace/studios/this_studio/Pose-app/lightning_pose_app/ui/train_infer.py", line 781, in _determine_dataset_type
    self.allow_context = is_context_dataset(
  File "/teamspace/studios/this_studio/Pose-app/lightning_pose_app/utilities.py", line 60, in is_context_dataset
    for frame in frames_in_dir:
TypeError: iteration over a 0-d array
INFO: Received SIGTERM signal. Gracefully terminating streamlit_video.work...

Could you please provide guidance on what might be causing this issue and how to resolve it? 
Best regards

**Comment by themattinthehatt** [comment] 2024-09-06 17:38
@Freddie-Faulich just checking in on this again - do you see the files in your project folder that @Shmuel-columbia mentioned? (`CollectedData.csv` and `labeled-data/<name_of_video>/selected_frames.csv`)

**Comment by agosztolai** [comment] 2024-09-12 10:20
Hi, we are still struggling with importing the Sleap labels. 

To begin with, the conversion code that you provide had several bugs.
1) It did not respect the ordering of the keypoints in sleep, so they were mixed up. This likely is not an issue for model training if the model does not use a skeleton.
2) It makes wrong keypoint-image matching. Only the first image for a given video was matches correctly to the keypoints for that image, by design of the code
3) It did not correctly treat points that were unlabeled. These points should be exported as NANs, but they were spurious numbers instead. 

I have fixed all these issues, and happy to share the code.

However, beyond all this, I am still struggling to use the Lightning Pose all on the cloud. I upload all the files and I can even use the 'Check labels' feature. However, it does not upload to Label Studio automatically.

I am playing with the .XML and .yaml files not that set up the studio, but this is taking a lot of time...

Could you please help? I am attaching the ColectedData.csv. In addition, there is a selected_frames.csv in every video folder.

![Screenshot 2024-09-12 at 12 18 14](https://github.com/user-attachments/assets/7304f541-ec6d-4e63-b820-57947797073a)
 
![Screenshot 2024-09-12 at 12 19 29](https://github.com/user-attachments/assets/9eea1343-8d02-4c6a-a5e6-ca3c62e97482)

![Screenshot 2024-09-12 at 12 20 08](https://github.com/user-attachments/assets/d7f13107-8928-47ab-852d-d10fdde761d7)

**Comment by agosztolai** [comment] 2024-09-12 12:45
Final update: I have managed to train a model and it works awesome! I still do not know how to use the Label Studio, but the rest works. 

Please let me know if you are interested in the revised sleap-to-lightning conversion code. This was essential to make the model work!

**Comment by themattinthehatt** [comment] 2024-09-12 13:46
@agosztolai yes please share your revised sleap-to-LP conversion code! apologies that you ran into issues with this, we'll take a look

> I still do not know how to use the Label Studio
can you describe the issue(s) that you are having here? are you able to see the login page at least?

**Comment by agosztolai** [comment] 2024-09-12 13:51
Here you go. 

Re Label Studio: I was expecting that after I upload the .csv and image files, these would become labeled images that I can manipulate in Label Studio. This didn't happen. I have also duplicated the mouse example into a new project and the corresponding labels likewise didn't upload. Yet, when you extract the images using the Pose-app, these appear automatically in Label Studio. 

Not a dealbreaker for me, but it would be nice to have an automatic updating feature, or at least a stable protocol.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Written by: Adam Gosztolai

Script to convert SLEAP project to Lightning Pose project

Usage:
$ python convertSLP2LP.py --slp_file /path/to/<project>.pkg.slp --lp_dir /path/to/lp/dir

Arguments:
--slp_file    Path to the SLEAP project file (.pkg.slp)
--lp_dir      Path to the output LP project directory

"""

import argparse
import io
import json
import os

import h5py
import numpy as np
import pandas as pd
import csv

import PIL.Image as Image
import cv2

def extract_frames_from_pkg_slp(file_path, base_output_dir, project_name='converted_project', scorer='adam'):
    
    #create directories
    if not os.path.exists(base_output_dir):
        os.makedirs(base_output_dir)
        os.makedirs(os.path.join(base_output_dir,"labeled-data"))
        os.makedirs(os.path.join(base_output_dir,"videos"))
        
    #parse .slp file
    with h5py.File(file_path, 'r') as hdf_file:
        # Identify video names
        video_names = {}
        for video_group_name in hdf_file.keys():
            if video_group_name.startswith('video'):
                source_video_path = f'{video_group_name}/source_video'
                if source_video_path in hdf_file:
                    source_video_json = hdf_file[source_video_path].attrs['json']
                    source_video_dict = json.loads(source_video_json)
                    video_filename = source_video_dict['backend']['filename']
                    video_names[video_group_name] = video_filename
                    
        # Extract and save images for each video
        data_frames = []
        for video_group, video_filename in video_names.items():
            scorer_row, bodyparts_row, coords_row = None, None, None
            output_dir = os.path.join(
                base_output_dir, "labeled-data", os.path.basename(video_filename).split('.')[0]
            )
            if not os.path.exists(output_dir):
                os.makedirs(output_dir)

            # extract labeled frames and save them in a separate directory for each video
            if video_group in hdf_file and 'video' in hdf_file[video_group]:
                video_data = hdf_file[f'{video_group}/video'][:]
                frame_numbers = hdf_file[f'{video_group}/frame_numbers'][:]
                frame_names = []
                for i, (img_bytes, frame_number) in enumerate(zip(video_data, frame_numbers)):
                    img = Image.open(io.BytesIO(np.array(img_bytes, dtype=np.uint8)))
                    img = np.array(img)

                    frame_name = f"img{str(frame_number).zfill(8)}.png"
                    cv2.imwrite(f"{output_dir}/{frame_name}", img)
                    frame_names.append(frame_name)
                    print(f"Saved frame {frame_number} as {frame_name}")
                    
                # Write to CSV file
                with open(f"{output_dir}/selected_frames.csv", 'w', newline='') as file:
                    writer = csv.writer(file)
                    for filename in frame_names:
                        writer.writerow([filename])
                    
            # extract coordinates and save them in a separate directory for each video
            if video_group in hdf_file and 'frames' in hdf_file:
                frames_dataset = hdf_file['frames']
                frame_references = {
                    frame['frame_id']: frame['frame_idx']
                    for frame in frames_dataset
                    if frame['video'] == int(video_group.replace('video', ''))
                }

                # Extract instances and points
                points_dataset = hdf_file['points']
                instances_dataset = hdf_file['instances']
                
                data = []
                for frame_id in frame_references.keys():
                    for i in range(len(instances_dataset)):
                        if frame_id==instances_dataset[i]['frame_id']:
                            point_id_start = instances_dataset[i+1]['point_id_start']
                            point_id_end = instances_dataset[i+1]['point_id_end']
                            break
                        
                    points = points_dataset[point_id_start:point_id_end]

                    keypoints_flat = []
                    for kp in points:
                        x, y, vis = kp['x'], kp['y'], kp['visible']
                        if np.isnan(x) or np.isnan(y) or vis==False:
                            x, y = None, None
                        keypoints_flat.extend([x, y])

                    frame_idx = frame_references[frame_id]
                    data.append([frame_idx] + keypoints_flat)
                        
                # parse data
                metadata_json = hdf_file['metadata'].attrs['json']
                metadata_dict = json.loads(metadata_json)
                nodes = metadata_dict['nodes']
                
                keypoints = [node['name'] for node in nodes]
                keypoints_ids = [n['id'] for n in metadata_dict['skeletons'][0]['nodes']]
                keypoints_ordered = [keypoints[idx] for idx in keypoints_ids]

                columns = [
                    'frame'
                ] + [
                    f'{kp}_x' for kp in keypoints_ordered
                ] + [
                    f'{kp}_y' for kp in keypoints_ordered
                ]
                scorer_row = ['scorer'] + [f'{scorer}'] * (len(columns) - 1)
                bodyparts_row = ['bodyparts'] + [f'{kp}' for kp in keypoints_ordered for _ in (0, 1)]
                coords_row = ['coords'] + ['x', 'y'] * len(keypoints_ordered)

                labels_df = pd.DataFrame(data, columns=columns)
                video_base_name = os.path.basename(video_filename).split('.')[0]
                labels_df['frame'] = labels_df['frame'].apply(
                    lambda x: (
                        f"labeled-data/{video_base_name}/"
                        f"img{str(int(x)).zfill(8)}.png"
                    )
                )
                labels_df = labels_df.groupby('frame', as_index=False).first()
                data_frames.append(labels_df)
     
                    
        # Combine all data frames into a single DataFrame
        combined_df = pd.concat(data_frames, ignore_index=True)
            
        header_df = pd.DataFrame(
            [scorer_row, bodyparts_row, coords_row],
            columns=combined_df.columns
        )
        final_df = pd.concat([header_df, combined_df], ignore_index=True)
        final_df.columns = [None] * len(final_df.columns)  # Set header to None
        
        # Save concatenated labels                
        final_df.to_csv(os.path.join(base_output_dir, "CollectedData.csv"), index=False, header=None)


parser = argparse.ArgumentParser()
parser.add_argument("--slp_file", type=str)
parser.add_argument("--lc_dir", type=str)
args = parser.parse_args()
slp_file = args.slp_file
dlc_dir = args.lc_dir

print(f"Converting SLEAP project to LC project located at {dlc_dir}")

# Extract and save labeled data from SLEAP project
extract_frames_from_pkg_slp(slp_file, dlc_dir)

```

**Comment by agosztolai** [comment] 2024-09-12 14:15
There was a little typo in the code, now fixed!

**Comment by themattinthehatt** [comment] 2024-09-12 15:07
> it would be nice to have an automatic updating feature
This is exactly what should be happening, not sure what the issue is. Would you be able to share your .pkg.slp file through email? Then we can try to debug specifically with your file.

Thanks for sharing your updated conversion code! @Shmuel-columbia

**Comment by Shmuel-columbia** [comment] 2024-09-13 20:35
Thanks for sharing your code!

Could you please provide more details about the changes you've made or the issues you're encountering? If possible, we'd appreciate a sample of your SLEAP file to test on our end.

**Closed** 2024-11-01 14:38 UTC
